export const Physics = [
     "Units and Measurements" ,
     "Motion in a Straight Line",
     "Motion in a Plane" ,
     "Laws of Motion" ,
     "Work, Energy, and Power" ,
     "System of Particles and Rotational Motion" ,
     "Gravitation" ,
     "Mechanical Properties of Solids" ,
     "Mechanical Properties of Fluids" ,
     "Thermal Properties of Matter" ,
     "Thermodynamics" ,
     "Kinetic Theory" ,
     "Oscillations" ,
     "Waves",
     "Electric Charges and Fields" ,
     "Electrostatic Potential and Capacitance" ,
     "Current Electricity" ,
     "Moving Charges and Magnetism" ,
     "Magnetism and Matter" ,
     "Electromagnetic Induction" ,
     "Alternating Current" ,
     "Electromagnetic Waves" ,
     "Ray Optics and Optical Instruments" ,
     "Wave Optics" ,
     "Dual Nature of Radiation and Matter" ,
     "Atoms" ,
     "Nuclei" ,
     "Semiconductor Electronics" 
]


export const Chemistry = [
     "Some Basic Concepts of Chemistry" ,
     "Structure of Atom" ,
     "Classification of Elements and Periodicity in Properties" ,
     "Chemical Bonding and Molecular Structure" ,
     "States of Matter: Gases and Liquids" ,
     "Thermodynamics" ,
     "Equilibrium" ,
     "Redox Reactions" ,
     "Hydrogen" ,
     "The s-Block Elements (Alkali and Alkaline Earth metals)" ,
     "Some p-Block Elements" ,
     "Organic Chemistry - Some Basic Principles and Techniques" ,
     "Hydrocarbons" ,
     "Environmental Chemistry" ,
     "Solid State" ,
     "Solutions" ,
     "Electrochemistry" ,
     "Chemical Kinetics" ,
     "Surface Chemistry" ,
     "General Principles and Processes of Isolation of Elements" ,
     "The p-Block Elements" ,
     "The d- and f-Block Elements" ,
     "Coordination Compounds" ,
     "Haloalkanes and Haloarenes" ,
     "Alcohols, Phenols, and Ethers" ,
     "Aldehydes, Ketones and Carboxylic Acids" ,
     "Organic Compounds Containing Nitrogen" ,
     "Biomolecules" ,
     "Polymers" ,
     "Chemistry in Everyday Life" 
]

export const Biology = [
 "Diversity of Living Organisms" ,
 "Structural Organisation in Animals and Plants" ,
 "Cell Structure and Function" ,
 "Biomolecules" ,
 "Enzymes and Metabolism" ,
 "Plant Physiology" ,
 "Respiration in Plants" ,
 "Photosynthesis in Higher Plants" ,
 "Transport in Plants" ,
     "Mineral Nutrition" ,
     "Human Physiology" ,
     "Locomotion and Movement" ,
     "Neural Control and Coordination" ,
     "Reproduction in Organisms" ,
     "Reproductive Health" ,
     "Genetics and Evolution" ,
     "Biotechnology and Its Applications" ,
     "Biotechnology - Principles and Processes" ,
     "Human Health and Disease" ,
     "Microbes in Human Welfare" ,
     "Ecology and Environment" ,
     "Biodiversity and Its Conservation"
]