export const Physics = [
  { "topic": "Units and Measurements" },
  { "topic": "Kinematics" },
  { "topic": "Laws of Motion" },
  { "topic": "Work, Energy, and Power" },
  { "topic": "Motion of System of Particles and Rigid Body" },
  { "topic": "Gravitation" },
  { "topic": "Properties of Bulk Matter" },
  { "topic": "Thermodynamics" },
  { "topic": "Behaviour of Perfect Gas and Kinetic Theory" },
  { "topic": "Oscillations and Waves" },
  { "topic": "Electrostatics" },
  { "topic": "Current Electricity" },
  { "topic": "Magnetic Effects of Current and Magnetism" },
  { "topic": "Electromagnetic Induction and Alternating Currents" },
  { "topic": "Electromagnetic Waves" },
  { "topic": "Optics" },
  { "topic": "Dual Nature of Matter and Radiation" },
  { "topic": "Atoms and Nuclei" },
  { "topic": "Electronic Devices" },
  { "topic": "Experimental and Practical Physics" }
]

  

export const Chemistry = [
  { "topic": "Some Basic Concepts of Chemistry" },
  { "topic": "Structure of Atom" },
  { "topic": "Classification of Elements and Periodicity in Properties" },
  { "topic": "Chemical Bonding and Molecular Structure" },
  { "topic": "States of Matter: Gases and Liquids" },
  { "topic": "Thermodynamics" },
  { "topic": "Equilibrium" },
  { "topic": "Redox Reactions" },
  { "topic": "Hydrogen" },
  { "topic": "The s-Block Element (Alkali and Alkaline Earth metals)" },
  { "topic": "Some p-Block Elements" },
  { "topic": "Organic Chemistry - Some Basic Principles and Techniques" },
  { "topic": "Hydrocarbons" },
  { "topic": "Environmental Chemistry" },
  { "topic": "Solid State" },
  { "topic": "Solutions" },
  { "topic": "Electrochemistry" },
  { "topic": "Chemical Kinetics" },
  { "topic": "Surface Chemistry" },
  { "topic": "General Principles and Processes of Isolation of Elements" },
  { "topic": "The p-Block Elements" },
  { "topic": "The d- and f-Block Elements" },
  { "topic": "Coordination Compounds" },
  { "topic": "Haloalkanes and Haloarenes" },
  { "topic": "Alcohols, Phenols, and Ethers" },
  { "topic": "Aldehydes, Ketones and Carboxylic Acids" },
  { "topic": "Organic Compounds Containing Nitrogen" },
  { "topic": "Biomolecules" },
  { "topic": "Polymers" },
  { "topic": "Chemistry in Everyday Life" }
]

export const Biology =[
  { "topic": "Diversity in the Living World" },
  { "topic": "Biological Classification" },
  { "topic": "Plant Kingdom" },
  { "topic": "Animal Kingdom" },
  { "topic": "Morphology of Flowering Plants" },
  { "topic": "Anatomy of Flowering Plants" },
  { "topic": "Structural Organisation in Animals" },
  { "topic": "Cell Structure and Function" },
  { "topic": "Biomolecules" },
  { "topic": "Cell Cycle and Cell Division" },
  { "topic": "Transport in Plants" },
  { "topic": "Mineral Nutrition" },
  { "topic": "Photosynthesis in Higher Plants" },
  { "topic": "Respiration in Plants" },
  { "topic": "Plant Growth and Development" },
  { "topic": "Digestion and Absorption" },
  { "topic": "Breathing and Exchange of Gases" },
  { "topic": "Body Fluids and Circulation" },
  { "topic": "Excretory Products and Their Elimination" },
  { "topic": "Locomotion and Movement" },
  { "topic": "Neural Control and Coordination" },
  { "topic": "Chemical Coordination and Integration" },
  { "topic": "Reproduction in Organisms" },
  { "topic": "Sexual Reproduction in Flowering Plants" },
  { "topic": "Human Reproduction" },
  { "topic": "Reproductive Health" },
  { "topic": "Principles of Inheritance and Variation" },
  { "topic": "Molecular Basis of Inheritance" },
  { "topic": "Evolution" },
  { "topic": "Human Health and Disease" },
  { "topic": "Strategies for Enhancement in Food Production" },
  { "topic": "Microbes in Human Welfare" },
  { "topic": "Biotechnology - Principles and Processes" },
  { "topic": "Biotechnology and Its Applications" },
  { "topic": "Organisms and Populations" },
  { "topic": "Ecosystem" },
  { "topic": "Biodiversity and Conservation" },
  { "topic": "Environmental Issues" }
]
